name: Criar instalador Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descarregar projeto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Criar instalador
        run: npm run dist:win

      - name: Guardar instalador
        uses: actions/upload-artifact@v4
        with:
          name: Tarkov-HUD-PT-Setup
          path: dist/*.exe
